spring.application.name=notes

spring.security.user.name=${USER_NAME}
spring.security.user.password=${USER_PASSWORD}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.app.jwtSecret=${MY_SECRET}
spring.app.jwtExpirationMs=${JWT_EXP}
frontend.url=${FRONTEND_URL}


logging.level.org.springframework.security=DEBUG